### ISSUE TITLE
Time Zone layer buttons don't work 

### ISSUE THREAD

**Issue by farahsalah** [WorldWindEarth/explorer#14]
The button next to the time zone layer does not seem to do anything, and the one next to it displays an opacity slider that also does not do anything. I also believe that adding the current time in each time zone as the user hovers over it would be a useful enhancement.

**Comment by emxsys** [comment]
Determining the current time in each time zone is being prototyped in the https://github.com/emxsys/WorldWindExplorer/commits/develop branch; it requires changes for picking prototyped in the Emxsys WebWorldWind fork:  https://github.com/emxsys/WebWorldWind/commits/develop branch.

**Comment by emxsys** [comment]
Applying the opacity from the layer to the shapefile's color alpha channels is being prototyped in the https://github.com/emxsys/WorldWindExplorer/commits/develop branch.

**Comment by emxsys** [comment]
The time zone opacity is now controlled in the Settings.
