### ISSUE TITLE
Improve branding of application

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/explorer#30]
The name "**World Wind Explorer**" can be misconstrued as an app for exploring the world's _winds_.   It's not readily apparent in this context that "World Wind" is a NASA organization. The application/project should be rebranded such that the organization and name are distinguishable.  Ideas:

- **WorldWind Explorer** : concatenate "World Wind"
- **NASA WorldWind Explorer** : add NASA to concatenated WorldWind
- **NASA WorldWind** **_Explorer_** : leverage typography / colors / logos 

Also, include credits to third party open-source projects in the README.

**Comment by PJHogan** [comment]
How about just calling it Earth Explorer?

-Patrick

**Comment by emxsys** [comment]
**NASA Earth Explorer** (so as to distinguish between the USGS Earth Explorer) looks to be applicable and not in use.

**Comment by PJHogan** [comment]
I like it.
