### ISSUE TITLE
Set Apache Expires and Cache-Control HTTP headers

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/explorer#79]
Set the generation of Expires and Cache-Control HTTP headers according to a short age (24 hours?) to ensure updates to web app are visible to clients.

### Apache Module mod_expires
https://httpd.apache.org/docs/current/mod/mod_expires.html

_"This module controls the setting of the Expires HTTP header and the max-age directive of the Cache-Control HTTP header in server responses. The expiration date can set to be relative to either the time the source file was last modified, or to the time of the client access.
These HTTP headers are an instruction to the client about the document's validity and persistence. If cached, the document may be fetched from the cache rather than from the source until this time has passed. After that, the cache copy is considered "expired" and invalid, and a new copy must be obtained from the source."_

**Comment by zglueck** [comment]
For the files server we wanted the examples to be the latest and greatest but also cached. Through some trial, error, and research we found that Chrome and Firefox would cache resources with the following Apache header configuration:
```
Header set Cache-Control: no-cache,max-age=0;
```
but, check for an update every page load. If the asset was updated the client would immediately get the new version. It adds an extra network hop, but doesn't download the entire asset in the event it is unchanged.

There is some more discussion on this issue:
https://github.com/NASAWorldWind/WebWorldWind/issues/296

**Comment by emxsys** [comment]
Updated .htaccess and added:
```XML
<IfModule mod_headers.c>
Header set Cache-Control: no-cache,max-age=0;
</IfModule>
```

**Comment by emxsys** [comment]
Need to ensure the static resources, e.g., shapefiles, images and libraries are cache-able.

**Comment by emxsys** [comment]
Added .htaccess files with cache control directives for the static resources.
